package ma.querdos.util;

import static ma.querdos.util.ByteManipulation.hexStringToByteArray;

/**
 * Created by Querdos on 10/07/2015.
 * Copyright 2015 - Hamza ESSAYEGH
 */
@SuppressWarnings("unused")
public final class Tag {

    public static final byte[] ACQUIRER_IDENTIFIER                          = hexStringToByteArray("9F01");
    public static final byte[] ADDITIONAL_TERMINAL_CAPABILITIES             = hexStringToByteArray("9F40");
    public static final byte[] AMOUNT_AUTHORIZED                            = hexStringToByteArray("81");
    public static final byte[] AUTHORIZED_AMOUNT                            = hexStringToByteArray("9F02");
    public static final byte[] AMOUNT_OTHER_BINARY                          = hexStringToByteArray("9F04");
    public static final byte[] AMOUNT_OTHER_NUMERIC                         = hexStringToByteArray("9F03");
    public static final byte[] AMOUNT_REFERENCE_CURRENCY                    = hexStringToByteArray("9F3A");
    public static final byte[] APPLICATION_CRYPTOGRAM                       = hexStringToByteArray("9F26");
    public static final byte[] APPLICATION_CURRENCY_CODE                    = hexStringToByteArray("9F42");
    public static final byte[] APPLICATION_CURRENCY_EXPONENT                = hexStringToByteArray("9F44");
    public static final byte[] APPLICATION_DISCRETIONARY_DATA               = hexStringToByteArray("9F05");
    public static final byte[] APPLICATION_EFFECTIVE_DATE                   = hexStringToByteArray("5F25");
    public static final byte[] APPLICATION_EXPIRATION_DATE                  = hexStringToByteArray("5F24");
    public static final byte[] APPLICATION_FILE_LOCATOR                     = hexStringToByteArray("94");
    public static final byte[] APPLICATION_IDENTIFIER_CARD                  = hexStringToByteArray("4F");
    public static final byte[] APPLICATION_IDENTIFIER_TERMINAL              = hexStringToByteArray("9F06");
    public static final byte[] APPLICATION_INTERCHANGE_PROFILE              = hexStringToByteArray("82");
    public static final byte[] APPLICATION_LABEL                            = hexStringToByteArray("50");
    public static final byte[] APPLICATION_PREFERRED_NAME                   = hexStringToByteArray("9F12");
    public static final byte[] APPLICATION_PRIMARY_ACCOUNT_NUMBER           = hexStringToByteArray("5A");
    public static final byte[] APPLICATION_PAN_SEQUENCE_NUMBER              = hexStringToByteArray("5F34");
    public static final byte[] APPLICATION_PRIORITY_INDICATOR               = hexStringToByteArray("87");
    public static final byte[] APPLICATION_REFERENCE_CURRENCY               = hexStringToByteArray("9F3B");
    public static final byte[] APPLICATION_REFERENCE_CURRENCY_EXPONENT      = hexStringToByteArray("9F43");
    public static final byte[] APPLICATION_TEMPLATE                         = hexStringToByteArray("61");
    public static final byte[] APPLICATION_TRANSACTION_COUNTER              = hexStringToByteArray("9F36");
    public static final byte[] APPLICATION_USAGE_CONTROL                    = hexStringToByteArray("9F07");
    public static final byte[] APPLICATION_VERSION_NUMBER                   = hexStringToByteArray("9F08");
    public static final byte[] AUTHORISATION_CODE                           = hexStringToByteArray("89");
    public static final byte[] AUTHORISATION_RESPONSE_CODE                  = hexStringToByteArray("8A");
    public static final byte[] BANK_IDENTIFIER_CODE                         = hexStringToByteArray("5F54");
    public static final byte[] CARD_RISK_MANAGEMENT_DATA_OBJ_LIST_1         = hexStringToByteArray("8C");
    public static final byte[] CARD_RISK_MANAGEMENT_DATA_OBJ_LIST_2         = hexStringToByteArray("8D");
    public static final byte[] CARDHOLDER_NAME                              = hexStringToByteArray("5F20");
    public static final byte[] CARDHOLDER_NAME_EXTENDED                     = hexStringToByteArray("9F0B");
    public static final byte[] CARDHOLDER_VERIFICATION_METHOD_LIST          = hexStringToByteArray("8E");
    public static final byte[] CARDHOLDER_VERIFICATION_METHOD_RESULTS       = hexStringToByteArray("9F34");
    public static final byte[] CERTIFICATION_AUTHORITY_PUBLIC_KEY_INDEX     = hexStringToByteArray("8F");
    public static final byte[] CERTIFICATION_AUTHORITY_PUBLIC_KEY_INDEX_BIS = hexStringToByteArray("9F22");
    public static final byte[] COMMAND_TEMPLATE                             = hexStringToByteArray("83");
    public static final byte[] CRYPTOGRAM_INFORMATION_DATA                  = hexStringToByteArray("9F27");
    public static final byte[] DATA_AUTHENTIFICATION_CODE                   = hexStringToByteArray("9F45");
    public static final byte[] DEDICATED_FILE_NAME                          = hexStringToByteArray("84");
    public static final byte[] DIRECTORY_DEFINITION_FILE_NAME               = hexStringToByteArray("9D");
    public static final byte[] EMV_PROPRIETARY_TEMPLATE                     = hexStringToByteArray("70");
    public static final byte[] FCI_ISSUER_DISCRETIONARY_DATA                = hexStringToByteArray("BF0C");
    public static final byte[] FCI_PROPRIETARY_TEMPLATE                     = hexStringToByteArray("A5");
    public static final byte[] FCI_TEMPALTE                                 = hexStringToByteArray("6F");
    public static final byte[] ICC_DYNAMIC_NUMBER                           = hexStringToByteArray("9F4C");
    public static final byte[] ICC_PIN_ENCIPHERMENT_PUBLIC_KEY_CERTIF       = hexStringToByteArray("9F2D");
    public static final byte[] ICC_PIN_ENCIPHERMENT_PUBLIC_KEY_EXPONENT     = hexStringToByteArray("9F2E");
    public static final byte[] ICC_PIN_ENCIPHERMENT_PUBLIC_KEY_REMAINDER    = hexStringToByteArray("9F2F");
    public static final byte[] ICC_PIN_PUBLIC_KEY_CERTIF                    = hexStringToByteArray("9F46");
    public static final byte[] ICC_PIN_PUBLIC_KEY_EXPONENT                  = hexStringToByteArray("9F47");
    public static final byte[] ICC_PIN_PUBLIC_KEY_REMAINDER                 = hexStringToByteArray("9F48");
    public static final byte[] INTERFACE_DEVICE_SERIAL_NUMBER               = hexStringToByteArray("9F1E");
    public static final byte[] INTERNATIONAL_BANK_ACCOUNT_NUMBER            = hexStringToByteArray("5F53");
    public static final byte[] ISSUER_ACTION_CODE_DEFAULT                   = hexStringToByteArray("9F0D");
    public static final byte[] ISSUER_ACTION_CODE_DENIAL                    = hexStringToByteArray("9F0E");
    public static final byte[] ISSUER_ACTION_CODE_ONLINE                    = hexStringToByteArray("9F0F");
    public static final byte[] ISSUER_APPLICATION_DATA                      = hexStringToByteArray("9F10");
    public static final byte[] ISSUER_AUTHENTIFICATION_DATA                 = hexStringToByteArray("91");
    public static final byte[] ISSUER_CODE_TABLE_INDEX                      = hexStringToByteArray("9F11");
    public static final byte[] ISSUER_COUNTRY_CODE                          = hexStringToByteArray("5F28");
    public static final byte[] ISSUER_COUNTRY_CODE_ALPHA2                   = hexStringToByteArray("5F55");
    public static final byte[] ISSUER_COUNTRY_CODE_ALPHA3                   = hexStringToByteArray("5F56");
    public static final byte[] ISSUER_IDENTIFICATION_NUMBER                 = hexStringToByteArray("42");
    public static final byte[] ISSUER_PUBLIC_KEY_CERTIFICATE                = hexStringToByteArray("90");
    public static final byte[] ISSUER_PUBLIC_EXPONENT                       = hexStringToByteArray("9F32");
    public static final byte[] ISSUER_PUBLIC_REMAINDER                      = hexStringToByteArray("92");
    public static final byte[] ISSUER_SCRIPT_COMMAND                        = hexStringToByteArray("86");
    public static final byte[] ISSUER_SCRIPT_IDENTIFIER                     = hexStringToByteArray("9F18");
    public static final byte[] ISSUER_SCRIPT_TEMPLATE_1                     = hexStringToByteArray("71");
    public static final byte[] ISSUER_SCRIPT_TEMPLATE_2                     = hexStringToByteArray("72");
    public static final byte[] LANGUAGE_PREFERENCE                          = hexStringToByteArray("5F2D");
    public static final byte[] LAST_ONLINE_ATC_REGISTER                     = hexStringToByteArray("9F13");
    public static final byte[] LOG_ENTRY                                    = hexStringToByteArray("9F4D");
    public static final byte[] LOG_FORMAT                                   = hexStringToByteArray("9F4F");
    public static final byte[] LOWER_CONSECUTIVE_OFFLINE_LIMIT              = hexStringToByteArray("9F14");
    public static final byte[] MERCHANT_CATEGORY_CODE                       = hexStringToByteArray("9F15");
    public static final byte[] MERCHANT_IDENTIFIER                          = hexStringToByteArray("9F16");
    public static final byte[] MERCHANT_NAME_AND_LOCATION                   = hexStringToByteArray("9F4E");
    public static final byte[] PERSONAL_IDENTIFICATION_NUMBER_TRY_COUNTER   = hexStringToByteArray("9F17");
    public static final byte[] POS_ENTRY_MODE                               = hexStringToByteArray("9F39");
    public static final byte[] PROCESSING_OPTIONS_DATA_OBJECT_LIST          = hexStringToByteArray("9F38");
    public static final byte[] RESPONSE_MESSAGE_TEMPLATE_FORMAT_1           = hexStringToByteArray("80");
    public static final byte[] RESPONSE_MESSAGE_TEMPLATE_FORMAT_2           = hexStringToByteArray("77");
    public static final byte[] SERVICE_CODE                                 = hexStringToByteArray("5F30");
    public static final byte[] SHORT_FILE_IDENTIFIER                        = hexStringToByteArray("88");
    public static final byte[] SIGNED_DYNAMIC_APPLICATION_DATA              = hexStringToByteArray("9F4B");
    public static final byte[] SIGNED_STATIC_APPLICATION_DATA               = hexStringToByteArray("93");
    public static final byte[] STATIC_DATA_AUTHENTIFICATION_TAG_LIST        = hexStringToByteArray("9F4A");
    public static final byte[] TERMINAL_CAPABILITIES                        = hexStringToByteArray("9F33");
    public static final byte[] TERMINAL_COUNTRY_CODE                        = hexStringToByteArray("9F1A");
    public static final byte[] TERMINAL_FLOOR_LIMIT                         = hexStringToByteArray("9F1B");
    public static final byte[] TERMINAL_IDENTIFICATION                      = hexStringToByteArray("9F1C");
    public static final byte[] TERMINAL_RISK_MANAGEMENT_DATA                = hexStringToByteArray("9F1D");
    public static final byte[] TERMINAL_TYPE                                = hexStringToByteArray("9F35");
    public static final byte[] TERMINAL_VERIFICATION_RESULTS                = hexStringToByteArray("95");
    public static final byte[] TRACK_1_DISCRETIONAY_DATA                    = hexStringToByteArray("9F1F");
    public static final byte[] TRACK_2_DISCRETIONAY_DATA                    = hexStringToByteArray("9F20");
    public static final byte[] TRACK_2_EQUIVALENT_DATA                      = hexStringToByteArray("57");
    public static final byte[] TRANSACTION_CERTIFICATE_HASH_VALUE           = hexStringToByteArray("98");
    public static final byte[] TRANSACTION_CERTIFICATE_DATA_OBJECT_LIST     = hexStringToByteArray("97");
    public static final byte[] TRANSACTION_CURENCY_CODE                     = hexStringToByteArray("5F2A");
    public static final byte[] TRANSACTION_CURRENCY_EXPONENT                = hexStringToByteArray("5F36");
    public static final byte[] TRANSACTION_DATE                             = hexStringToByteArray("9A");
    public static final byte[] TRANSACTION_PERSONAL_IDENT_NUMBER_DATA       = hexStringToByteArray("99");
    public static final byte[] TRANSACTION_REFERENCE_CURRENCY_CODE          = hexStringToByteArray("9F3C");
    public static final byte[] TRANSACTION_REFERENCE_CURRENCY_EXPONENT      = hexStringToByteArray("9F3D");
    public static final byte[] TRANSACTION_SEQUENCE_COUNTER                 = hexStringToByteArray("9F41");
    public static final byte[] TRANSACTION_STATUS_INFORMATION               = hexStringToByteArray("9B");
    public static final byte[] TRANSACTION_TIME                             = hexStringToByteArray("9F21");
    public static final byte[] TRANSACTION_TYPE                             = hexStringToByteArray("9C");
    public static final byte[] UNPREDICTABLE_NUMBER                         = hexStringToByteArray("9F37");
    public static final byte[] UPPER_CONSECUTIVE_OFFLINE_LIMIT              = hexStringToByteArray("9F23");

}
